version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    networks:
      - prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - '--web.listen-address=0.0.0.0:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin1234
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - prometheus
    ports:
      - 8080:3000
    volumes:
      - ./grafana_datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    depends_on:
      - prometheus

networks:
  prometheus:
      name: prometheus